services:
  - type: web
    name: my-java-app
    env: custom
    region: us-west
    buildCommand: |
      apt-get update && \
      apt-get install -y openjdk-17-jdk && \
      java -version && \
      javac -version && \
      mkdir -p bin && \
      javac -d bin $(find src -name '*.java')
    startCommand: >
      export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64 &&
      export PATH=$JAVA_HOME/bin:$PATH &&
      java -cp bin MyLibrary.Main
    instances: 1
