services:
  - type: web
    name: my-java-app
    env: docker
    buildCommand: ""  # We're using Docker, so no build command is necessary
    dockerfilePath: ./Dockerfile  # Path to the Dockerfile in the root directory
    startCommand: "java -cp bin com.example.Main"  # Change to the fully qualified name of Main class if inside a package
    instances: 1  # Number of instances to run
    region: us-west  # Adjust the region if necessary
